CREATE TABLE fnbs (
id UUID NOT NULL PRIMARY KEY,
code VARCHAR(50) NOT NULL UNIQUE,
menu VARCHAR(50) NOT NULL,
kind VARCHAR(50), 
price INT NOT NULL,
raw_mat TEXT[],
raw_amount INT[],
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL
);
